# Site settings

baseurl = "http://deepstertrading.com/"
languageCode = "en-us"
title = "Deepster Trading Co."
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-80840190-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Deepster Trading Company - Homepage"
	description = "Deepster Trading Company is family run company established in 2016. Deepster Trading Company is a consumer oriented company. We are committed to Quality products and Quality services. Over the past almost few years, we have built a solid reputation based on these two principles. We deal in all types of Toddler friendly products. We also do consulting for other dealers, wholesalers & consumers. Our networks of dependable worldwide suppliers guarantee the quality and services. In addition, we ensure value for money products."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "contact@deepstertrading.com"

    # Link custom assets relative to /statuc
    custom_css = []
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "Deepster Trading Co."
		services = "Our Services"
		# portfolio = "Our Catalog"
		team = "Our Team"
		about = "Our Story"
		contact = "Contact Us"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    #[[menu.postpend]]
    #    url = "http://gohugo.io"
    #    name = "External link"
    #    weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Welcome To Deepster Trading Co."
		subtitle = "Customers Come First!"
		buttonText = "Tell me more"


	# Services section
	[params.services]
        enable = true
		title = "Services"
		subtitle = "What we offer"

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-shopping-cart"
                title = "E-Commerce"
                description = "Selling goods in various online marketplaces - Amazon, Flipkart and Snapdeal"

            [[params.services.row.list]]
                icon = "fa-laptop"
                title = "Consulting"
                description = "Take our help to figure out the inner workings of online marketplaces and the secrets of selling products online."

            [[params.services.row.list]]
                icon = "fa-lock"
                title = "Market Research"
                description = "We will help you find the right product-market fit for your brand's products"

	# Portfolio section
	[params.portfolio]
        enable = false
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Products we sell"

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
        enable = true
		title = "Our Story"
		subtitle = "How it all started"
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "July 2016"
			title = "Our Humble Beginnings"
			description = "On a lazy weekend, two brothers sat down brainstorming ideas for marketplace businesses."

		[[params.about.events]]
			img = "2.jpg"
			date = "September 2016"
			title = "An Trading Company is Born"
			description = "After looking at the business viability and contacting sourcing partners, the brothers incorporated the Comapany."

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2016"
			title = "First Product Launch"
			description = "Countless hours later, the launch of our first Prodcut on Amazon India online marketplace"

		[[params.about.events]]
			img = "4.jpg"
			date = "March 2017"
			title = "Path to Profitability"
			description = "After many ups and downs, the company finally turned a profit."


	# Team section
	[params.team]
        enable = true
		title = "Our Amazing Team"
		subtitle = "The group that came together"
		description = ""

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "pradeep.png"
			name = "Pradeep Dantuluri"
			position = "CEO / Founder"
			social = [
				["fa-twitter", "#pradeepvarma"],
				["fa-facebook", "#pradeep122"],
				["fa-linkedin", "#pradeep122"]
			]

		[[params.team.members]]
			img = "sandeep.png"
			name = "Sandeep Dantuluri"
			position = "COO / Founder"
			social = [
				["fa-twitter", "#sandeepvarmad"],
				["fa-facebook", "#sandeepvarmad"],
				["fa-linkedin", "#sandeepvarmad"]
			]

	# Client section
    [params.clients_list]
        enable = false

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "designmodo.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"


	# Contact section
	[params.contact]
        enable = true
		title = "Get in touch"
		subtitle  = "Please state your purpose and association."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "2016 @ Deepster Trading Company "

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "#deepstertrading"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "#deepstertrading"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "#deepstertrading"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#privacy"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#terms"
